# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ferbass.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: ferbass
  avatar: avatar.png
  gravatar: d6eff6d7984430dd23a2ba550bfe6767 # email md5 hash
  description: "A website with blog posts and pages" # used by search engines
  
  # Header and footer text
  header_text: >
     
  footer_text: >
   ferbass.com is released under a <a href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons BY-NC License</a>. <br />
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  
  # Icons
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "ferbass"
  google_plus: 
  instagram: 
  linkedin: "http://br.linkedin.com/in/fernandobass"
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "fer_bass"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: UA-7317580-3 # tracking id, e.g. "UA-000000-01"
  disqus_shortname: ferbass
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
